[build]
  publish = "dist/Stock-Portfolio"
  command = "ng build --prod"

[[redirects]]
  from = "/v8/*"
  to = "https://query1.finance.yahoo.com:splat"
  status = 200

[[headers]]
  for = "/v8/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
