export const stockRecommendations = [
  {
    Name: 'Team17 Group PLC',
    Symbol: 'TM17.L',
    recommendation: 'Hold',
    startDate: '2020-06-08',
    endDate: 'None',
    return: '',
  },
  {
    Name: 'Paradox Interactive',
    Symbol: 'PDX.ST',
    recommendation: 'Hold',
    startDate: '2020-06-05',
    endDate: '',
    return: '',
  },
  {
    Name: '11 bit Studios',
    Symbol: '11C.F',
    recommendation: 'Buy',
    startDate: '2020-06-08',
    endDate: '',
    return: '',
  },
  {
    Name: 'BigBen Interactive',
    Symbol: 'BIG.PA',
    recommendation: 'Hold',
    startDate: '2020-06-03',
    endDate: '',
    return: '',
  },
  {
    Name: "Don't Nod Entertainment",
    Symbol: 'ALDNE.PA',
    recommendation: 'Buy',
    startDate: '2020-06-09',
    endDate: '',
    return: '',
  },
  {
    Name: 'Remedy Entertainment ',
    Symbol: 'REMEDY.HE',
    recommendation: 'Hold',
    startDate: '2020-06-05',
    endDate: '',
    return: '',
  },
];
